version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
    - "5423:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  server:
    build:
      context: ./Server
    env_file:
      - ./.env
    volumes:
      - ./Server:/usr/src/app
    links:
      - db
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./Frontend
    env_file:
      - ./.env
    volumes:
      - ./Frontend:/usr/src/app
    links:
      - server
    ports:
      - "3000:3000"